name: Python fibbonaci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Typecheck mypy
        run: |
          pip install mypy
          mypy python/
      - name: Run unittests
        run: |
          cd python/
          python -m unittest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docker container
        uses: docker/build-push-action@v3
        with:
          context: python/
          push: false # Switch to true after setting up dockerhub and a login step
          tags: fib-app:latest
